<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => 'Ключ авторизации',
    'Budget' => 'Бюджет',
    'Chasi' => 'Часы',
    'Create' => 'Создать',
    'Created At' => 'Создать в',
    'Distsiplina' => 'Дисциплина',
    'Distsiplinas' => 'Дисциплины',
    'Dogovor' => 'Договор',
    'Ekzamen' => 'Экзамен',
    'Email' => '',
    'Fakultet' => 'Факультет',
    'Fakultets' => 'Факультеты',
    'Fio' => 'ФИО',
    'First Name' => 'Имя',
    'ID' => 'Номер',
    'It is recommended you use an upgraded browser to display the {type} control properly.' => '',
    'K Nedel' => 'К-во недель',
    'Kafedra' => 'Кафедра',
    'Kafedras' => 'Кафедры',
    'Konsultacii' => 'Консультации',
    'Kontrolnii' => 'Контрольные',
    'Kurs' => 'Курс',
    'Kursovoi' => 'Курсовой',
    'Laboratornie' => 'Лабораторные',
    'Last Name' => 'Фамилия',
    'Lekcii' => 'Лекции',
    'Modul' => 'Модуль',
    'N Semestra' => 'Номер семестра',
    'Nagruzka Prepods' => 'Нагрузка на преподавателей',
    'Nazvanie' => 'Название',
    'Norma' => 'Норма',
    'Normas' => 'Нормы нагрузки',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Period' => 'Период',
    'Periods' => 'Периоды',
    'Podgrupchel' => 'Человек в подгруппе',
    'Prakticheskie' => 'Практические',
    'Prepodavatel' => 'Преподаватель',
    'Prepodavatels' => 'Преподаватели',
    'Raschet Nagruzkis' => 'Расчет нагрузки',
    'Specialnost' => 'Специальность',
    'Specialnosts' => 'Специальности',
    'Srs' => 'СРС',
    'Status' => 'Состояние',
    'Stavka' => 'Ставка',
    'Stavkas' => 'Ставки преподавателей',
    'Update' => 'Изменить',
    'Updated At' => 'Изменить в',
    'Username' => 'Логин',
    'Users' => 'Пользователи',
    'Zachet' => 'Зачет',
    'Zvanie' => 'Звание',
];
