<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Действия',
    'Active' => 'Активировать',
    'Add Book' => 'Добавить книгу',
    'All' => 'Все',
    'Are you sure to delete this item?' => 'Удалить эту строку?',
    'Book Listing' => 'Список книг',
    'CSV' => '',
    'Clear selection' => 'Снять выделение',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Delete' => 'Удалить',
    'Disable any popup blockers in your browser to ensure proper download.' => '',
    'Download Selected' => 'Скачать выделенное',
    'Excel' => '',
    'Expand' => 'Расширить',
    'Expand All' => 'Расширить все',
    'Export' => 'Экспорт',
    'Export All Data' => 'Экспортировать все данные',
    'Export Page Data' => 'Экспортировать данные страницы',
    'ExportWorksheet' => '',
    'Generated' => '',
    'Generating the export file. Please wait...' => 'Создание файла экспорта. Пожалуйста, подождите...',
    'Grid Export' => 'Экспорт таблицы',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Inactive' => 'Неактивно',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Library' => 'Библиотека',
    'Microsoft Excel 95+' => '',
    'No data found' => 'Данные не найдены',
    'Ok to proceed?' => 'OK для продолжения',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Экспорт в PDF',
    'Page' => 'Страница',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Вы можете закрыть это окно после сохранения Вашего фала',
    'Reset Grid' => 'Сбросить таблицу',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Изменяйте ширину столбцов перетаскиванием их краев',
    'Show all data' => 'Показать все данные',
    'Show first page data' => 'Показать первую страницу',
    'Tab Delimited Text' => '',
    'Text' => 'Текст',
    'The CSV export file will be generated for download.' => 'Файл экспорта CSV будет доступен для скачивания',
    'The EXCEL export file will be generated for download.' => 'Файл экспорта EXCEL будет доступен для скачивания',
    'The HTML export file will be generated for download.' => 'Файл экспорта HTML будет доступен для скачивания',
    'The JSON export file will be generated for download.' => 'Файл экспорта JSON будет доступен для скачивания',
    'The PDF export file will be generated for download.' => 'Файл экспорта PDF будет доступен для скачивания',
    'The TEXT export file will be generated for download.' => 'Файл экспорта TEXT будет доступен для скачивания',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'Update' => 'Изменить',
    'View' => 'Просмотреть',
    'Yii2 Grid Export (PDF)' => 'Экспорт таблицы (PDF)',
    'export' => 'экспорт',
    'grid-export' => 'экспорт таблицы',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '© Григорий Терешко КН-2',
];
