<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => '',
    'Budget' => '',
    'Chasi' => '',
    'Create' => '',
    'Created At' => '',
    'Distsiplina' => '',
    'Distsiplinas' => '',
    'Dogovor' => '',
    'Ekzamen' => '',
    'Email' => '',
    'Fakultet' => '',
    'Fakultets' => '',
    'Fio' => '',
    'First Name' => '',
    'ID' => '',
    'It is recommended you use an upgraded browser to display the {type} control properly.' => '',
    'K Nedel' => '',
    'Kafedra' => '',
    'Kafedras' => '',
    'Konsultacii' => '',
    'Kontrolnii' => '',
    'Kurs' => '',
    'Kursovoi' => '',
    'Laboratornie' => '',
    'Last Name' => '',
    'Lekcii' => '',
    'Modul' => '',
    'N Semestra' => '',
    'Nagruzka Prepods' => '',
    'Nazvanie' => '',
    'Norma' => '',
    'Normas' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Period' => '',
    'Periods' => '',
    'Podgrupchel' => '',
    'Prakticheskie' => '',
    'Prepodavatel' => '',
    'Prepodavatels' => '',
    'Raschet Nagruzkis' => '',
    'Specialnost' => '',
    'Specialnosts' => '',
    'Srs' => '',
    'Status' => '',
    'Stavka' => '',
    'Stavkas' => '',
    'Update' => '',
    'Updated At' => '',
    'Username' => '',
    'Users' => '',
    'Zachet' => '',
    'Zvanie' => '',
];
